name: Build SunamoMsgReader

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoMsgReader
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMsgReader/SunamoMsgReader.csproj

    - name: Build
      run: dotnet build SunamoMsgReader/SunamoMsgReader.csproj --configuration Release --no-restore

  test:
    name: Test SunamoMsgReader.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMsgReader.Tests/SunamoMsgReader.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoMsgReader.Tests/SunamoMsgReader.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoMsgReader.Tests/SunamoMsgReader.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
